LOCAL_PATH := device/samsung/coreprimevelte

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mrvl 
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := coreprimevelte
TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/recovery.fstab

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1932525568
BOARD_USERDATAIMAGE_PARTITION_SIZE := 5518655488
BOARD_CACHEIMAGE_PARTITION_SIZE := 209715200
BOARD_FLASH_BLOCK_SIZE := 131072

BOARD_HAS_NO_SELECT_BUTTON := true

BOARD_CUSTOM_MKBOOTIMG := $(LOCAL_PATH)/tools/marvell-mkbootimg
BOARD_CUSTOM_BOOTIMG_MK := $(LOCAL_PATH)/custom_mkbootimg.mk
# Kernel
TARGET_KERNEL_SOURCE := kernel/samsung/coreprimevelte
TARGET_KERNEL_CONFIG := pxa1908_coreprimevelte_eur_defconfig
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-linux-android-
KERNEL_TOOLCHAIN := /opt/toolchains/aarch64-linux-android-4.8/bin
BOARD_KERNEL_BASE         := 0x10000000
BOARD_KERNEL_CMDLINE      := 
BOARD_KERNEL_PAGESIZE     := 2048
BOARD_KERNEL_SEPARATED_DT := true
BOARD_KERNEL_IMAGE_NAME   := zImage
BOARD_DTBTOOL_ARGS        :=
BOARD_MKBOOTIMG_ARGS      := --unknown 0x3000000 --tags_offset 0x00000100 --seandroidenforce
BOARD_MKRECOVERYIMG_ARGS  := --unknown 0x3000000 --tags_offset 0x00000100 --seandroidenforce
BOARD_UBOOT_ARGS          := -A arm64 -O linux -T kernel -C gzip -a 01000000 -e 01000000 -n "pxa1928dkb linux"
BOARD_UBOOT_IMAGE_NAME    := uImage


#twrp
TW_THEME:= portrait_hdpi
RECOVERY_SDCARD_ON_DATA := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
BOARD_HAS_NO_REAL_SDCARD := true
TW_EXCLUDE_MTP := true
TW_MTP_DEVICE := /dev/usb_mtp_gadget
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_NO_REBOOT_BOOTLOADER := true
TW_HAS_DOWNLOAD_MODE := true
TW_EXCLUDE_SUPERSU := true
TW_EXCLUDE_ENCRYPTED_BACKUPS := true

MRVL_ION := true
BOARD_USE_VIVANTE_GRALLOC := true
HDMI_SUPPORT_3D := true

MRVL_INTERFACE_ANIMATION := true

MRVL_LAUNCH_DMS_IN_SURFACEFLINGER := true

TARGET_FORCE_CPU_UPLOAD := true

# Init
TARGET_PROVIDES_INIT := true
TARGET_PROVIDES_INIT_TARGET_RC := true
